# Generated by Django 3.2.23 on 2024-03-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('default_image', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='默认图片')),
                ('release_date', models.DateField(verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '新闻管理',
                'verbose_name_plural': '新闻管理',
                'db_table': 'tb_news',
            },
        ),
    ]
