# Generated by Django 3.2.23 on 2024-03-15 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_from', models.CharField(max_length=10)),
                ('release_date', models.DateField(verbose_name='发布日期')),
                ('character1', models.CharField(max_length=1000, verbose_name='第一大段')),
                ('img1', models.ImageField(default='', max_length=200, null=True, upload_to='', verbose_name='图片1')),
                ('character2', models.CharField(max_length=1000, null=True, verbose_name='第二大段')),
                ('img2', models.ImageField(default='', max_length=200, null=True, upload_to='', verbose_name='图片2')),
                ('character3', models.CharField(max_length=1000, null=True, verbose_name='第三大段')),
                ('img3', models.ImageField(default='', max_length=200, null=True, upload_to='', verbose_name='图片3')),
                ('character4', models.CharField(max_length=1000, null=True, verbose_name='第四大段')),
            ],
            options={
                'verbose_name': '新闻内容',
                'verbose_name_plural': '新闻内容',
                'db_table': 'tb_news_content',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news_content'),
        ),
    ]
