# Generated by Django 3.2.23 on 2024-03-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20240315_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_content',
            name='tag1',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='news_content',
            name='tag2',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='news_content',
            name='tag3',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
