# Generated by Django 3.2.23 on 2024-03-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('news', '0003_auto_20240315_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.news_video'),
        ),
    ]
