# Generated by Django 3.2.23 on 2024-03-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='release_date',
            field=models.DateTimeField(null=True, verbose_name='发布日期'),
        ),
    ]
