# Generated by Django 3.2.23 on 2024-03-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_from', models.CharField(max_length=10)),
                ('release_date', models.DateField(verbose_name='发布日期')),
                ('video', models.CharField(max_length=1000, verbose_name='视频内容')),
            ],
            options={
                'verbose_name': '新闻视频',
                'verbose_name_plural': '新闻视频',
                'db_table': 'tb_news_video',
            },
        ),
    ]
