# Generated by Django 3.2.23 on 2024-03-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240312_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(default='http://127.0.0.1:8080/images/profile/default.jpg', max_length=200),
        ),
    ]
