# Generated by Django 3.2.23 on 2024-03-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
